### ISSUE TITLE
cannot build with exceptions

### ISSUE THREAD

**Issue by xantares** [tpoechtrager/wclang#10]
Hi again,
Why are exceptions disabled ?
Would it require to link against a cross-compiled version of llvm custom stdlib "libc++" ?
xan.

**Comment by xantares** [comment]
hello,
although not advertised from v3.6 changelog, there as been work in clang regarding windows exceptions
from http://planet.clang.org/:

- Clang gained initial support for Win64 SEH IR emission, http://reviews.llvm.org/rL226760

- Initial support for Win64 SEH catch handlers has landed. See the commit message for current missing functionality: http://reviews.llvm.org/rL225904

- Reid Kleckner has posted an RFC on approaches to representing structured exception handling (SEH) in LLVM IR. This is the exception handling model used on Windows:
http://article.gmane.org/gmane.comp.compilers.clang.devel/39152

- The documentation on MSVC compatibility has been updated to represent the current state of affairs. Clang has also gained support for rethrowing MS C++ exceptions. r222731, r222733.

Does this allow to generate exception with mingw ?

**Comment by tpoechtrager** [comment]
Yes, 64-bit SEH exceptions are working now with trunk (3.7), but not with 3.6, as 3.6 was branched before exception support was added.

I have removed the `-fno-exception` flag for 3.7 + 64-bit.
