### ISSUE TITLE
Ubuntu version string of clang may not correct match in CMakeLists.txt

### ISSUE THREAD

**Issue by firodj** [tpoechtrager/wclang#11]
Then default **clang --version** on Ubuntu 14.04.1 string is:
Ubuntu clang version **3.4-1ubuntu3** (tags/RELEASE_34/final) (based on LLVM 3.4)

which the string REGEX_REPLACE match pattern should become: `".*version ([0-9\\.]+).*"` instead `".*version ([0-9\\.]+) .*"` when detecting the CLANG_VERSION (we dont need a space after the version number)

**Comment by tpoechtrager** [comment]
Thanks - fixed.
