### ISSUE TITLE
Clang: warning: argument unused during compilation:

### ISSUE THREAD

**Issue by svost** [tpoechtrager/wclang#18]
Hello.
Can I ignore these messages or something went wrong?
novacoin@nvcnode:/opt/wclang/bin$ ./w64-clang++ -v
Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-w64-windows-gnu
Thread model: posix
clang: warning: argument unused during compilation: '-nostdinc'
clang: warning: argument unused during compilation: '-fno-exceptions'
clang: warning: argument unused during compilation: '-isystem /usr/bin/../lib/clang/3.6/include'
clang: warning: argument unused during compilation: '-isystem /usr/x86_64-w64-mingw32/include'
clang: warning: argument unused during compilation: '-isystem /usr/x86_64-w64-mingw32/include/../../../usr/lib/gcc/x86_64-w64-mingw32/4.9-posix/include/c++'
clang: warning: argument unused during compilation: '-isystem /usr/x86_64-w64-mingw32/include/../../../usr/lib/gcc/x86_64-w64-mingw32/4.9-posix/include/c++/x86_64-w64-mingw32'
novacoin@nvcnode:/opt/wclang/bin$

**Comment by tpoechtrager** [comment]
Hello svost, you can safely ignore them. These warnings will only show up with `-v` (because you aren't compiling anything).
