### ISSUE TITLE
llvm 3.8 vs exceptions ?

### ISSUE THREAD

**Issue by xantares** [tpoechtrager/wclang#21]
hi
it seems clang 3.8 supports emitting exceptions now!
can the fno-exception flag be removed ?

**Comment by tpoechtrager** [comment]
Please have a look and let me know. :-)

**Comment by xantares** [comment]
Ok, as soon as clang hits the repos

**Comment by baszalmstra** [comment]
@xantares Are you still looking into this?

**Comment by xantares** [comment]
@baszalmstra, yes, I'm still waiting for clang 3.8 to land in archlinux

**Comment by baszalmstra** [comment]
@xantares Ah I see, would you happen to have any clue on when that will happen?

**Comment by xantares** [comment]
It does support compiling with exceptions enabled, on both 32/64 bits arches!
cmdargs.exceptions can be set to 0 in src/wclang.cpp for clang >= 3.8

cc @baszalmstra

**Comment by tpoechtrager** [comment]
> It does support compiling with exceptions enabled, on both 32/64 bits arches!
> cmdargs.exceptions can be set to 0 in src/wclang.cpp for clang >= 3.8

Compiling was never a problem.

> unfortunately on 32 bits it compiles but fails to link:
> /usr/i686-w64-mingw32/include/c++/5.3.0/ext/new_allocator.h:110: undefined reference to `_Unwind_Resume'

So nothing has changed. Wrong exceptions are used -- it's not just a missing symbol.

**Comment by xantares** [comment]
@tpoechtrager, ok, sorry
see you next time for 3.9!
