### ISSUE TITLE
wclang: warning: cannot find clang intrinsics directory

### ISSUE THREAD

**Issue by pisto** [tpoechtrager/wclang#34]
Title.

mingw version:
```
[pisto@pisto ~]$ x86_64-w64-mingw32-g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/x86_64-w64-mingw32-g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-w64-mingw32/7.1.0/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../configure --prefix=/usr --bindir=/usr/bin --includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --with-gnu-as --with-gnu-ld --verbose --without-newlib --disable-multilib --disable-plugin --with-system-zlib --disable-nls --without-included-gettext --disable-win32-registry --enable-languages=c,c++,objc,obj-c++,fortran --with-bugurl=http://bugzilla.redhat.com/bugzilla --with-cloog --enable-threads=posix --enable-libgomp --target=x86_64-w64-mingw32 --with-sysroot=/usr/x86_64-w64-mingw32/sys-root --with-gxx-include-dir=/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++
Thread model: posix
gcc version 7.1.0 20170502 (Fedora MinGW 7.1.0-1.fc26) (GCC) 
```

**Comment by tpoechtrager** [comment]
What's the output of `echo "int main(){}"|clang -xc - -o /dev/null -v`?

**Comment by pisto** [comment]
https://da.gd/rWt1b

**Comment by tpoechtrager** [comment]
Do you get the same warning with OSXCross?

**Comment by pisto** [comment]
I'll build it and check. Does that build with the SDK command line only package?

**Comment by tpoechtrager** [comment]
No. I copied the logic from OSXCross. Please test.

**Comment by pisto** [comment]
No it doesn't happen with osxcross.

**Comment by pisto** [comment]
With c65691d8ce0d3175a24907c259184e6b64953482 it still happens.

**Comment by tpoechtrager** [comment]
You are on Fedora 26 x86_64?

**Comment by pisto** [comment]
yes

**Comment by pisto** [comment]
I think I figured out the problem, on Fedora 26 ccache works with clang, but wclang gets confused by that. If I remove the clang ccache symlinks it appears to work. I cannot confirm yet that my program works because I'm having some issues with thread_local variables destructors, but I'm fairly confident that it will work completely.

**Comment by tpoechtrager** [comment]
Is this still an issue? Do you really rely on ccache support?

**Comment by pisto** [comment]
No I don't rely on it

**Comment by DanRStevens** [comment]
I've run into the same error message on Ubuntu 18.04, where I've been using ccache to speedup rebuilds.

**Comment by tpoechtrager** [comment]
Should work now. You must also create ccache symlinks for wclang.

i.e.: `ln -s $(which ccache) w32-clang`, i686-w64-mingw32-clang, ... and so on
