### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by mati865** [tpoechtrager/wclang#38]
Hello, I've created PPA for Ubuntu providing [prebuild wclang releases](https://launchpad.net/~mati865/+archive/ubuntu/wclang).

To automatize it I've set up project mirroring this repository on [Launchpad](https://launchpad.net/wclang). Once a day it looks for new commits and builds new release if there are any. If you have Launchpad account I can give you full permissions/ownership.

I'm currently holding packaging scripts for Debian and Ubuntu on a [branch of my fork](https://github.com/mati865/wclang/tree/ubuntu) but I'll have to move them to separate repository or merge it with this repository to allow automatic imports.

Decision is up to you if you want those scripts in official repository on separate branch.

**Comment by tpoechtrager** [comment]
Thanks. Could you file a pull request?

**Comment by mati865** [comment]
Sure but you will have to create empty branch (GitHub doesn't allow creating new branch in PR).

**Comment by tpoechtrager** [comment]
Master branch is fine.
