### ISSUE TITLE
i686-w64-clang: command not found

### ISSUE THREAD

**Issue by DarknightCanada** [tpoechtrager/wclang#49]
`root@kali:/bin/wclang# i686-w64-clang -wc-help
bash: i686-w64-clang: command not found`

even when I add it to the @PATH still getting the error

**Comment by tpoechtrager** [comment]
It's `i686-w64-mingw32-clang`.

**Comment by DarknightCanada** [comment]
sorry typo
`make install
[100%] Built target wclang
Install the project...
-- Install configuration: "Release"
-- Installing: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/w32-clang -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/w32-clang++ -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/w64-clang -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/w64-clang++ -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/i686-w64-mingw32-clang -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/i686-w64-mingw32-clang++ -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/x86_64-w64-mingw32-clang -> wclang
-- Symlinking: /root/HTB/rastalab/PEzor/wclang/_prefix_/bin/x86_64-w64-mingw32-clang++ -> wclang`

bash: i686-w64-mingw32-clang: command not found

**Comment by DarknightCanada** [comment]
added to the patch as well but not working

export PATH=/root/HTB/rastalab/PEzor/wclang/_prefix_/bin/wclang:$PATH
