### ISSUE TITLE
Will you ever create a clang cross compiler tool to cross compile for MacOS?

### ISSUE THREAD

**Issue by retrooper** [tpoechtrager/wclang#53]

**Comment by tpoechtrager** [comment]
You should have a look at my other projects. ;)

**Comment by retrooper** [comment]
Saw this: https://github.com/tpoechtrager/osxcross , Isn't that only for cross compiling for Linux on a MACOS?

**Comment by tpoechtrager** [comment]
No. It's the other way around...

**Comment by retrooper** [comment]
Oh ok. Thanks.

**Comment by retrooper** [comment]
Your projects really help out a ton! :heart:
