### ISSUE TITLE
Simple spec file to build on Fedora

### ISSUE THREAD

**Issue by crayxt** [tpoechtrager/wclang#6]
Hi,

Recently I created a simple spec file to package wclang into RPM for Fedora Linux, see
https://gist.github.com/crayxt/cb07a39f450c53fb9ff7

Just thought it might be useful for someone else.

Thanks,

**Comment by maci0** [comment]
i don't think we need the i486, i586 and so on wrappers on fedora.
Target here is mainly i686-w64-mingw32 and x86_64-w64-mingw32
It is what is used throughout the fedora mingw toolchain.

**Comment by tpoechtrager** [comment]
@maci0: Forgot to close this - wclang uses cmake now and only installs the triples which are really present on the system.

**Comment by maci0** [comment]
@tpoechtrager I see, I'll look into creating a proper .spec file then.
The one from @crayxt seems to miss a lot of mingw specific stuff commonly used in fedora as well.

**Comment by maci0** [comment]
@tpoechtrager see https://github.com/maci0/rpmbuild/commit/6df05f336b9c422b9b6a863fcc1226d530c004b2
for a fedora compliant spec file :)

**Comment by tpoechtrager** [comment]
@maci0: Thanks! :-)

**Comment by maci0** [comment]
@tpoechtrager I submitted a review request to fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1252471

**Comment by crayxt** [comment]
In my defense I can say that I intended for minimal working configuration. thank you @maci0 for your efforts!
